### PR TITLE
allowing logging version above 1.6 and beyond 1.x

### PR DESCRIPTION
**Pull request by gingerlime**
see TwP/logging#108

### CODE REVIEW

**Comment by TwP** [comment]
Already fixed by a different PR

**Comment by gingerlime** [comment]
I might be wrong, but I think the other PR will only allow upgrading to 1.x, but not to 2.x though...

**Comment by TwP** [comment]
Correct. There will be corresponding version bump to logging-rails when logging 2.0 is released. Logging 2.0 is definitely _not_ backwards compatible. Hence the major version bump.

**Comment by gingerlime** [comment]
I see. It seems to be working fine for us though (`logging` 2.0 and `logging-rails` - with the removed dependency), but maybe we're not using all features of `logging` to manage to break anything...(?)

**Pull request closed without merging**
